services:
  okx_btc:
    build: .
    container_name: okx_btc
    restart: unless-stopped
    environment:
      - VALIDATE=1
    command: /app/okx_btc_prod.yaml
    volumes:
      - ./donnees:/app/donnees
      - ./okx_btc_prod.yaml:/app/okx_btc_prod.yaml:ro
    mem_limit: 512m
    cpus: "1.0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/donnees/okx_live.sqlite || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s

  okx_eth:
    build: .
    container_name: okx_eth
    restart: unless-stopped
    environment:
      - VALIDATE=1
    command: /app/okx_eth_prod.yaml
    volumes:
      - ./donnees:/app/donnees
      - ./okx_eth_prod.yaml:/app/okx_eth_prod.yaml:ro
    mem_limit: 512m
    cpus: "1.0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/donnees/okx_live.sqlite || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
