version: "3.8"

services:
  ccxt_universel:
    build: .
    container_name: ccxt_universel_v2
    environment:
      - TZ=Europe/Paris
      # Optionnel: tu peux injecter des variables pour l’entrypoint
      # - YAML=ccxt_batch.yaml
      # - TASKS=binance_btc_1m_jan2024,okx_multi_ohlcv
    volumes:
      - ./donnees:/app/donnees
      - ./ccxt_batch.yaml:/app/ccxt_batch.yaml:ro
    # Pas de "command": on laisse l'entrypoint décider selon les args/env
    restart: unless-stopped
